import javax.swing.ImageIcon;

import java.awt.event.KeyEvent;

/**
 * 
 * @author FlorianF
 */
public class GUI extends javax.swing.JFrame {
	private Communication communication;
	
	/**
	 * Creates new form GUI
	 */
	public GUI(Communication communication) {
		this.communication = communication;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		final ImageIcon plaatje = new ImageIcon(getClass().getResource(
				"/intproject.jpg")); // user added

		jPasswordField1 = new javax.swing.JPasswordField();
		MainPanel = new javax.swing.JPanel();
		UserPanel = new javax.swing.JPanel();
		userScrollpane = new javax.swing.JScrollPane();
		userList = new javax.swing.JList<String>();
		ChatPanel = new javax.swing.JPanel();
		chatScrollpane = new javax.swing.JScrollPane();
		chatTextPane = new javax.swing.JTextPane();
		SendPanel = new javax.swing.JPanel();
		inputText = new javax.swing.JTextField();
		sendBtn = new javax.swing.JButton();
		Titel = new javax.swing.JLabel();
		backgroundLabel = new javax.swing.JLabel();

		jPasswordField1.setText("jPasswordField1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMaximumSize(new java.awt.Dimension(800, 450));
		setMinimumSize(new java.awt.Dimension(815, 450));
		setPreferredSize(new java.awt.Dimension(800, 450));
		getContentPane().setLayout(null);

		MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(255, 255, 255), 5));
		MainPanel.setOpaque(false);

		userList.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
		userList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Jacco", "Florian", "Joey", "Sander" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		userScrollpane.setViewportView(userList);

		javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(
				UserPanel);
		UserPanel.setLayout(UserPanelLayout);
		UserPanelLayout.setHorizontalGroup(UserPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				userScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 158,
				Short.MAX_VALUE));
		UserPanelLayout.setVerticalGroup(UserPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				userScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 328,
				Short.MAX_VALUE));

		chatScrollpane.setAutoscrolls(true);

		chatTextPane.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
		chatTextPane
				.setText("                                                               Chat Venster");
		chatScrollpane.setViewportView(chatTextPane);

		javax.swing.GroupLayout ChatPanelLayout = new javax.swing.GroupLayout(
				ChatPanel);
		ChatPanel.setLayout(ChatPanelLayout);
		ChatPanelLayout.setHorizontalGroup(ChatPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				chatScrollpane));
		ChatPanelLayout.setVerticalGroup(ChatPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				chatScrollpane));

		SendPanel.setOpaque(false);
		SendPanel.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				SendPanelKeyPressed(evt);
			}
		});

		inputText.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
		inputText.setText("Chat Input");
		inputText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inputTextActionPerformed(evt);
			}
		});

		sendBtn.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
		sendBtn.setText("Send!");
		sendBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout SendPanelLayout = new javax.swing.GroupLayout(
				SendPanel);
		SendPanel.setLayout(SendPanelLayout);
		SendPanelLayout
				.setHorizontalGroup(SendPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								SendPanelLayout
										.createSequentialGroup()
										.addComponent(
												inputText,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												486,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												sendBtn,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												90, Short.MAX_VALUE)));
		SendPanelLayout.setVerticalGroup(SendPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				SendPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(inputText,
								javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(sendBtn,
								javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(
				MainPanel);
		MainPanel.setLayout(MainPanelLayout);
		MainPanelLayout
				.setHorizontalGroup(MainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								MainPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												UserPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												MainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																SendPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																ChatPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		MainPanelLayout
				.setVerticalGroup(MainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								MainPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												MainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																UserPanel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																MainPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				ChatPanel,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				SendPanel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));

		getContentPane().add(MainPanel);
		MainPanel.setBounds(10, 40, 780, 360);

		Titel.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
		Titel.setForeground(new java.awt.Color(255, 255, 255));
		Titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Titel.setText("Ad-Hoc Wifi Chat");
		getContentPane().add(Titel);
		Titel.setBounds(0, 0, 800, 40);

		backgroundLabel.setIcon(plaatje); // useradded
		getContentPane().add(backgroundLabel);
		backgroundLabel.setBounds(0, -40, 920, 530);

		pack();
	}// </editor-fold>

	private void inputTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {
		sendChat(inputText.getText());
	}

	private void SendPanelKeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			sendChat(inputText.getText());
		}
	}

	// Program Functions

	private void sendChat(String text) {

	}

	private void receiveChat(String text) {

	}

	// Uitgaande van een string die de users splitst met ; zonder verdere
	// spaties etc.
	private void updateUsers(String users) {
		String[] lijstje = new String[users.split(";").length];
		for (int i = 0; i < users.split(";").length; i++) {
			if (users.split(";")[i] != null) {
				lijstje[i] = users.split(";")[i];
			}
		}
		userList.setListData(lijstje);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI(new Communication()).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel ChatPanel;
	private javax.swing.JPanel MainPanel;
	private javax.swing.JPanel SendPanel;
	private javax.swing.JLabel Titel;
	private javax.swing.JPanel UserPanel;
	private javax.swing.JLabel backgroundLabel;
	private javax.swing.JScrollPane chatScrollpane;
	private javax.swing.JTextPane chatTextPane;
	private javax.swing.JTextField inputText;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton sendBtn;
	private javax.swing.JList<String> userList;
	private javax.swing.JScrollPane userScrollpane;
	// End of variables declaration
}
